version: '3'
services:
  ia-frontend:
    image: ia-frontend
    stdin_open: true
    ports:
      - 3000:3000
    env_file:
      - .env.dev
    restart: always
    command: npm run start:dev
    volumes: # This is where the magic happens!
      - ./src:/usr/src/client/src
      - ./public:/usr/src/client/public
    networks:
      - mern-app
  ia-backend:
    image: ia-backend
    ports:
      - 3001:3001
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
